// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdo__VwLcTGRcwQ_64fS1s9PhIRcmOzOo',
    appId: '1:736803406916:web:81b278bcb49afc450d6811',
    messagingSenderId: '736803406916',
    projectId: 'firebase-user-database',
    authDomain: 'fir-user-database-1995f.firebaseapp.com',
    storageBucket: 'firebase-user-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-y-5lcIVvX76SgL6lduJB8IXRVzPaix8',
    appId: '1:736803406916:android:9a54666689a2266c0d6811',
    messagingSenderId: '736803406916',
    projectId: 'firebase-user-database',
    storageBucket: 'firebase-user-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJS92ip8ysXxN0pbWU7JC5Mp1q8Z35rQ',
    appId: '1:736803406916:ios:e61056a0554a11630d6811',
    messagingSenderId: '736803406916',
    projectId: 'firebase-user-database',
    storageBucket: 'firebase-user-database.firebasestorage.app',
    iosBundleId: 'com.example.firebaseUserDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjJS92ip8ysXxN0pbWU7JC5Mp1q8Z35rQ',
    appId: '1:736803406916:ios:e61056a0554a11630d6811',
    messagingSenderId: '736803406916',
    projectId: 'firebase-user-database',
    storageBucket: 'firebase-user-database.firebasestorage.app',
    iosBundleId: 'com.example.firebaseUserDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdo__VwLcTGRcwQ_64fS1s9PhIRcmOzOo',
    appId: '1:736803406916:web:0cd746363392de220d6811',
    messagingSenderId: '736803406916',
    projectId: 'firebase-user-database',
    authDomain: 'fir-user-database-1995f.firebaseapp.com',
    storageBucket: 'firebase-user-database.firebasestorage.app',
  );
}
